# Generated by Django 5.0.2 on 2024-03-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ligne_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('date_debut', models.DateField(default=None)),
                ('date_fin', models.DateField(default=None)),
                ('statut', models.CharField(choices=[('A Produire', 'Aproduire'), ('En cours', 'Encours'), ('Terminé', 'Termine')], default='A Produire', max_length=30)),
                ('produits_requis', models.ManyToManyField(to='app.ligne_produit')),
            ],
        ),
    ]
