# Generated by Django 5.0.2 on 2024-03-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ligne_produit_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='production',
            name='date_fin',
        ),
    ]
