# Generated by Django 5.0.2 on 2024-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_production_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='produits_manquants',
            field=models.TextField(default=''),
        ),
    ]
