# Generated by Django 5.0.2 on 2024-03-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_production_produits_manquants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_produit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.element'),
        ),
    ]
