# Generated by Django 5.0.2 on 2024-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
