# Generated by Django 5.0.2 on 2024-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ligne_commande_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('details', models.TextField()),
                ('expiration', models.DateField(default=None, null=True)),
            ],
        ),
    ]
