# Generated by Django 5.0.2 on 2024-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_impression_code_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='by',
            field=models.TextField(default='Aucun'),
        ),
    ]
