# Generated by Django 4.2.10 on 2024-04-03 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_vente_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('prix', models.FloatField(max_length=10, null=True)),
                ('prix_achat', models.FloatField(default=0, max_length=10)),
                ('acompte', models.FloatField(max_length=10, null=True)),
                ('by', models.CharField(max_length=100)),
                ('date_commande', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('Delivré', 'Delivre'), ('Non delivré', 'Nondelivre')], default='Non delivré', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dépence_gain',
            name='by',
            field=models.TextField(default='/'),
        ),
    ]
